version: 1.2
workflows:
  - subclass: WDL
    name: Run_Splotch
    primaryDescriptorPath: /workflows/run_csplotch.wdl
    authors:
      - name: Matthew Smith-Erb
        email: msmitherb@nygenome.org
  - subclass: WDL
    name: Prepare_Count_Files
    primaryDescriptorPath: /workflows/prepare_count_files.wdl
    authors:
      - name: Matthew Smith-Erb
        email: msmitherb@nygenome.org